"""
Test Order Management Features
Tests for Phases 1-3: Order Editing, Status Workflow, and Devis Auto-Generation
"""
import requests
import json
from datetime import datetime

BASE_URL = "http://localhost:8000/api/v1"

# You'll need to get a valid token first by logging in
# Replace this with your actual admin token
TOKEN = None

def get_auth_headers():
    if not TOKEN:
        print("⚠️  No token set. Please login first.")
        return {}
    return {"Authorization": f"Bearer {TOKEN}"}

def login(email: str, password: str):
    """Login and get token"""
    global TOKEN
    response = requests.post(
        f"{BASE_URL}/auth/login",
        json={"email": email, "password": password}
    )
    if response.status_code == 200:
        TOKEN = response.json()["access_token"]
        print(f"✅ Logged in successfully")
        return True
    else:
        print(f"❌ Login failed: {response.text}")
        return False

def test_get_orders():
    """Test: Get all orders"""
    print("\n" + "="*80)
    print("TEST 1: Get All Orders")
    print("="*80)
    
    response = requests.get(
        f"{BASE_URL}/orders/",
        headers=get_auth_headers()
    )
    
    print(f"Status: {response.status_code}")
    if response.status_code == 200:
        data = response.json()
        print(f"✅ Found {data['total']} orders")
        if data['orders']:
            print(f"First order: {data['orders'][0]['order_number']} - Status: {data['orders'][0]['status']}")
        return data['orders']
    else:
        print(f"❌ Failed: {response.text}")
        return []

def test_accept_order(order_id: str):
    """Test: Accept an order (PENDING → PROCESSING)"""
    print("\n" + "="*80)
    print(f"TEST 2: Accept Order {order_id}")
    print("="*80)
    
    response = requests.post(
        f"{BASE_URL}/orders/{order_id}/accept",
        json={"notes": "Test acceptance"},
        headers=get_auth_headers()
    )
    
    print(f"Status: {response.status_code}")
    if response.status_code == 200:
        data = response.json()
        print(f"✅ Order accepted!")
        print(f"   Status: {data['status']}")
        print(f"   Order Number: {data['order_number']}")
        return data
    else:
        print(f"❌ Failed: {response.text}")
        return None

def test_update_order_items(order_id: str, product_id: str):
    """Test: Update order items"""
    print("\n" + "="*80)
    print(f"TEST 3: Update Order Items for {order_id}")
    print("="*80)
    
    payload = {
        "items": [
            {
                "product_id": product_id,
                "quantity": 5,
                "discount_percent": 10.0,
                "unit_price": 100.0
            }
        ]
    }
    
    response = requests.put(
        f"{BASE_URL}/orders/{order_id}/items",
        json=payload,
        headers=get_auth_headers()
    )
    
    print(f"Status: {response.status_code}")
    if response.status_code == 200:
        data = response.json()
        print(f"✅ Order items updated!")
        print(f"   Subtotal: {data['subtotal']}")
        print(f"   Total: {data['total_amount']}")
        print(f"   Items count: {len(data['items'])}")
        return data
    else:
        print(f"❌ Failed: {response.text}")
        return None

def test_confirm_order(order_id: str):
    """Test: Confirm order (should auto-generate devis)"""
    print("\n" + "="*80)
    print(f"TEST 4: Confirm Order {order_id} (Auto-generate Devis)")
    print("="*80)
    
    response = requests.post(
        f"{BASE_URL}/orders/{order_id}/confirm",
        headers=get_auth_headers()
    )
    
    print(f"Status: {response.status_code}")
    if response.status_code == 200:
        data = response.json()
        print(f"✅ Order confirmed!")
        print(f"   Status: {data['status']}")
        print(f"   Confirmed at: {data.get('confirmed_at', 'N/A')}")
        
        # Check if devis was generated by looking at order history
        print("\n   Checking for auto-generated devis...")
        history_response = requests.get(
            f"{BASE_URL}/orders/{order_id}/history",
            headers=get_auth_headers()
        )
        if history_response.status_code == 200:
            history = history_response.json()
            devis_entry = next((h for h in history if h['action'] == 'devis_generated'), None)
            if devis_entry:
                print(f"   ✅ Devis auto-generated: {json.loads(devis_entry['new_value'])['devis_number']}")
            else:
                print(f"   ⚠️  No devis generation found in history")
        
        return data
    else:
        print(f"❌ Failed: {response.text}")
        return None

def test_reject_order(order_id: str):
    """Test: Reject an order"""
    print("\n" + "="*80)
    print(f"TEST 5: Reject Order {order_id}")
    print("="*80)
    
    response = requests.post(
        f"{BASE_URL}/orders/{order_id}/reject",
        json={
            "reason": "Customer requested cancellation",
            "notes": "Test rejection"
        },
        headers=get_auth_headers()
    )
    
    print(f"Status: {response.status_code}")
    if response.status_code == 200:
        data = response.json()
        print(f"✅ Order rejected!")
        print(f"   Status: {data['status']}")
        print(f"   Stock reserved: {data['stock_reserved']}")
        return data
    else:
        print(f"❌ Failed: {response.text}")
        return None

def test_get_devis_list():
    """Test: Get all devis documents"""
    print("\n" + "="*80)
    print("TEST 6: Get All Devis Documents")
    print("="*80)
    
    response = requests.get(
        f"{BASE_URL}/documents/?type=devis",
        headers=get_auth_headers()
    )
    
    print(f"Status: {response.status_code}")
    if response.status_code == 200:
        data = response.json()
        print(f"✅ Found {data.get('total', 0)} devis documents")
        if data.get('documents'):
            for doc in data['documents'][:3]:
                print(f"   - {doc['document_number']}: {doc['status']} (Order: {doc.get('order_id', 'N/A')})")
        return data
    else:
        print(f"❌ Failed: {response.text}")
        return None

def run_all_tests():
    """Run all tests in sequence"""
    print("\n" + "="*80)
    print("ORDER MANAGEMENT SYSTEM - COMPREHENSIVE TESTS")
    print("="*80)
    
    # Use actual admin credentials
    email = "admin@nourdistribution.com"
    password = "AyoubOueslati2001#"
    
    if not login(email, password):
        print("\n❌ Cannot proceed without authentication")
        return
    
    # Test 1: Get orders
    orders = test_get_orders()
    
    if not orders:
        print("\n⚠️  No orders found. Please create an order first via the checkout flow.")
        return
    
    # Find a PENDING order for testing
    pending_order = next((o for o in orders if o['status'] == 'PENDING'), None)
    
    if pending_order:
        order_id = pending_order['id']
        print(f"\n📋 Using order: {pending_order['order_number']} (ID: {order_id})")
        
        # Test 2: Accept order
        accepted = test_accept_order(order_id)
        
        if accepted and accepted.get('items'):
            # Test 3: Update order items (get first product ID)
            product_id = accepted['items'][0]['product_id']
            test_update_order_items(order_id, product_id)
        
        # Test 4: Confirm order (auto-generates devis)
        test_confirm_order(order_id)
        
        # Test 6: Check devis list
        test_get_devis_list()
    else:
        print("\n⚠️  No PENDING orders found for testing accept/confirm workflow")
    
    # Find a PENDING order for rejection test
    orders = test_get_orders()  # Refresh list
    pending_for_reject = next((o for o in orders if o['status'] == 'PENDING'), None)
    
    if pending_for_reject:
        # Test 5: Reject order
        test_reject_order(pending_for_reject['id'])
    
    print("\n" + "="*80)
    print("TESTS COMPLETED")
    print("="*80)

if __name__ == "__main__":
    run_all_tests()
