"""Add new fields to charges table

Revision ID: 076239102050
Revises: 1acf4eaf73d7
Create Date: 2025-12-22 16:44:03.422913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076239102050'
down_revision: Union[str, None] = '1acf4eaf73d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charges', sa.Column('type', sa.Enum('FIXED', 'VARIABLE', name='chargetype'), nullable=True))
    op.add_column('charges', sa.Column('recurrence', sa.Enum('PONCTUEL', 'WEEKLY', 'MONTHLY', 'YEARLY', name='chargerecurrence'), nullable=True))
    op.add_column('charges', sa.Column('validated', sa.Boolean(), nullable=True))
    op.add_column('charges', sa.Column('supplier', sa.String(length=255), nullable=True))
    # op.alter_column('payments', 'payment_method',
    #            existing_type=sa.VARCHAR(length=100),
    #            type_=sa.Enum('especes', 'cheque', 'virement', 'carte', 'postal', 'mobile', 'autre', name='paymentmethodenum'),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_method',
               existing_type=sa.Enum('especes', 'cheque', 'virement', 'carte', 'postal', 'mobile', 'autre', name='paymentmethodenum'),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('charges', 'supplier')
    op.drop_column('charges', 'validated')
    op.drop_column('charges', 'recurrence')
    op.drop_column('charges', 'type')
    # ### end Alembic commands ###
