"""Add delivery models and client limits

Revision ID: 5191ddd45117
Revises: add_completed_status
Create Date: 2026-01-06 13:44:10.375973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5191ddd45117'
down_revision: Union[str, None] = 'add_completed_status'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_notes',
    sa.Column('delivery_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SHIPPED', 'DELIVERED', 'RETURNED', 'FAILED', name='deliverystatus'), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('facture_id', sa.UUID(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('carrier_name', sa.String(length=100), nullable=True),
    sa.Column('tracking_reference', sa.String(length=100), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['facture_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_notes_delivery_number'), 'delivery_notes', ['delivery_number'], unique=True)
    op.create_table('delivery_note_items',
    sa.Column('delivery_note_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_notes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('admin_notifications', 'target_roles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('admin_notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('admin_notifications', 'read_by',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('admin_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_admin_notifications_created', table_name='admin_notifications')
    op.drop_index('idx_admin_notifications_priority', table_name='admin_notifications')
    op.drop_index('idx_admin_notifications_read', table_name='admin_notifications')
    op.drop_index('idx_admin_notifications_type', table_name='admin_notifications')
    op.add_column('clients', sa.Column('credit_limit', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('current_balance', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('suspension_reason', sa.String(length=255), nullable=True))
    op.alter_column('payments', 'payment_method',
               existing_type=postgresql.ENUM('especes', 'cheque', 'virement', 'carte', 'postal', 'mobile', 'autre', name='paymentmethodenum'),
               nullable=False)
    op.alter_column('stock_alerts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('stock_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_stock_alerts_active', table_name='stock_alerts')
    op.drop_index('idx_stock_alerts_priority', table_name='stock_alerts')
    op.drop_index('idx_stock_alerts_product', table_name='stock_alerts')
    op.drop_index('idx_stock_alerts_type', table_name='stock_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_stock_alerts_type', 'stock_alerts', ['alert_type'], unique=False)
    op.create_index('idx_stock_alerts_product', 'stock_alerts', ['product_id'], unique=False)
    op.create_index('idx_stock_alerts_priority', 'stock_alerts', ['priority'], unique=False)
    op.create_index('idx_stock_alerts_active', 'stock_alerts', ['is_active'], unique=False)
    op.alter_column('stock_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_alerts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('payments', 'payment_method',
               existing_type=postgresql.ENUM('especes', 'cheque', 'virement', 'carte', 'postal', 'mobile', 'autre', name='paymentmethodenum'),
               nullable=True)
    op.drop_column('clients', 'suspension_reason')
    op.drop_column('clients', 'is_suspended')
    op.drop_column('clients', 'current_balance')
    op.drop_column('clients', 'credit_limit')
    op.create_index('idx_admin_notifications_type', 'admin_notifications', ['notification_type'], unique=False)
    op.create_index('idx_admin_notifications_read', 'admin_notifications', ['is_read'], unique=False)
    op.create_index('idx_admin_notifications_priority', 'admin_notifications', ['priority'], unique=False)
    op.create_index('idx_admin_notifications_created', 'admin_notifications', [sa.text('created_at DESC')], unique=False)
    op.alter_column('admin_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('admin_notifications', 'read_by',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('admin_notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('admin_notifications', 'target_roles',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_table('delivery_note_items')
    op.drop_index(op.f('ix_delivery_notes_delivery_number'), table_name='delivery_notes')
    op.drop_table('delivery_notes')
    # ### end Alembic commands ###
