"""Add guest_session_id to carts

Revision ID: 6d7735a07d38
Revises: 932c0c3bc376
Create Date: 2025-12-12 15:21:25.332374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7735a07d38'
down_revision: Union[str, None] = '932c0c3bc376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('carts_client_id_fkey', 'carts', type_='foreignkey')
    op.drop_column('carts', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('carts_client_id_fkey', 'carts', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
