"""Add document fields and enums

Revision ID: 85d955444897
Revises: 076239102050
Create Date: 2025-12-26 13:47:27.367112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d955444897'
down_revision: Union[str, None] = '076239102050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Explicitly create enums for PostgreSQL
    op.execute("COMMIT") # Enums cannot be created in a transaction block in some older PG versions, but usually fine. Safest to just run SQL.
    # Actually, let's use the sqlalchemy method which is cleaner
    from sqlalchemy.dialects import postgresql
    
    payment_terms = postgresql.ENUM('immediate', 'net30', 'net60', 'on_delivery', name='paymentterms')
    payment_terms.create(op.get_bind(), checkfirst=True)

    avoir_reason = postgresql.ENUM('return', 'damaged', 'error', 'cancellation', 'other', name='avoirreason')
    avoir_reason.create(op.get_bind(), checkfirst=True)
    
    op.add_column('documents', sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('payment_terms', sa.Enum('immediate', 'net30', 'net60', 'on_delivery', name='paymentterms'), nullable=True))
    op.add_column('documents', sa.Column('payment_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('avoir_reason', sa.Enum('return', 'damaged', 'error', 'cancellation', 'other', name='avoirreason'), nullable=True))
    
    # For payment_method, we need to handle the conversion from VARCHAR to ENUM
    # First create the type
    payment_method = postgresql.ENUM('especes', 'cheque', 'virement', 'carte', 'postal', 'mobile', 'autre', name='paymentmethodenum')
    payment_method.create(op.get_bind(), checkfirst=True)
    
    # Then alter with explicit USING clause
    op.execute("ALTER TABLE payments ALTER COLUMN payment_method TYPE paymentmethodenum USING payment_method::paymentmethodenum")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payment_method',
               existing_type=sa.Enum('especes', 'cheque', 'virement', 'carte', 'postal', 'mobile', 'autre', name='paymentmethodenum'),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('documents', 'avoir_reason')
    op.drop_column('documents', 'payment_deadline')
    op.drop_column('documents', 'payment_terms')
    op.drop_column('documents', 'valid_until')
    # ### end Alembic commands ###
