"""update models

Revision ID: 904ed82a6ae1
Revises: 4a3410b4f25b
Create Date: 2025-11-21 22:56:26.990114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904ed82a6ae1'
down_revision: Union[str, None] = '4a3410b4f25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('inventory_movements',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('STOCK_IN', 'STOCK_OUT', 'RESERVED', 'RELEASED', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('previous_stock', sa.Integer(), nullable=False),
    sa.Column('new_stock', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('short_description', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=False))
    op.add_column('products', sa.Column('hair_type', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('hair_texture', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('hair_length', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('hair_color', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('hair_origin', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('hair_quality', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('weight_grams', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('bundle_pieces', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('package_dimensions', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('reserved_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('max_stock_level', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('wholesale_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('supplier_sku', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_best_seller', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_new_arrival', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('main_image', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('additional_images', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('meta_title', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('meta_description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('search_keywords', sa.Text(), nullable=True))
    op.alter_column('products', 'cost_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_products_category', table_name='products')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'length')
    op.drop_column('products', 'category')
    op.drop_column('products', 'color')
    op.drop_column('products', 'texture')
    op.drop_column('products', 'suggested_price')
    op.add_column('suppliers', sa.Column('company_name', sa.String(length=255), nullable=False))
    op.add_column('suppliers', sa.Column('legal_name', sa.String(length=255), nullable=True))
    op.add_column('suppliers', sa.Column('whatsapp', sa.String(length=50), nullable=True))
    op.add_column('suppliers', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('suppliers', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('suppliers', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('suppliers', sa.Column('business_registration', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('vat_number', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('preferred_payment_method', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('shipping_terms', sa.String(length=255), nullable=True))
    op.add_column('suppliers', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('reliability_rating', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('quality_rating', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('communication_rating', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('is_preferred', sa.Boolean(), nullable=True))
    op.add_column('suppliers', sa.Column('tags', sa.JSON(), nullable=True))
    op.drop_index('ix_suppliers_name', table_name='suppliers')
    op.create_index(op.f('ix_suppliers_company_name'), 'suppliers', ['company_name'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_fiscal_id'), 'suppliers', ['fiscal_id'], unique=False)
    op.drop_column('suppliers', 'name')
    op.drop_column('suppliers', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('suppliers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_suppliers_fiscal_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_company_name'), table_name='suppliers')
    op.create_index('ix_suppliers_name', 'suppliers', ['name'], unique=False)
    op.drop_column('suppliers', 'tags')
    op.drop_column('suppliers', 'is_preferred')
    op.drop_column('suppliers', 'communication_rating')
    op.drop_column('suppliers', 'quality_rating')
    op.drop_column('suppliers', 'reliability_rating')
    op.drop_column('suppliers', 'lead_time_days')
    op.drop_column('suppliers', 'shipping_terms')
    op.drop_column('suppliers', 'preferred_payment_method')
    op.drop_column('suppliers', 'vat_number')
    op.drop_column('suppliers', 'business_registration')
    op.drop_column('suppliers', 'postal_code')
    op.drop_column('suppliers', 'state')
    op.drop_column('suppliers', 'address_line2')
    op.drop_column('suppliers', 'address_line1')
    op.drop_column('suppliers', 'whatsapp')
    op.drop_column('suppliers', 'legal_name')
    op.drop_column('suppliers', 'company_name')
    op.add_column('products', sa.Column('suggested_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('texture', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('color', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('length', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index('ix_products_category', 'products', ['category'], unique=False)
    op.alter_column('products', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'cost_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('products', 'search_keywords')
    op.drop_column('products', 'meta_description')
    op.drop_column('products', 'meta_title')
    op.drop_column('products', 'additional_images')
    op.drop_column('products', 'main_image')
    op.drop_column('products', 'is_new_arrival')
    op.drop_column('products', 'is_best_seller')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'supplier_sku')
    op.drop_column('products', 'retail_price')
    op.drop_column('products', 'wholesale_price')
    op.drop_column('products', 'max_stock_level')
    op.drop_column('products', 'reserved_quantity')
    op.drop_column('products', 'package_dimensions')
    op.drop_column('products', 'bundle_pieces')
    op.drop_column('products', 'weight_grams')
    op.drop_column('products', 'hair_quality')
    op.drop_column('products', 'hair_origin')
    op.drop_column('products', 'hair_color')
    op.drop_column('products', 'hair_length')
    op.drop_column('products', 'hair_texture')
    op.drop_column('products', 'hair_type')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'short_description')
    op.drop_table('product_images')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
