"""update models

Revision ID: 932c0c3bc376
Revises: 4a3410b4f25b
Create Date: 2025-12-10 15:35:30.496895
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '932c0c3bc376'
down_revision: Union[str, None] = '4a3410b4f25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create paymentstatus ENUM if it doesn't exist
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'paymentstatus') THEN
                CREATE TYPE paymentstatus AS ENUM ('NON_PAYE', 'PARTIEL', 'PAYE', 'EN_RETARD');
            END IF;
        END$$;
    """)

    # Add the payment_status column once
    op.add_column('documents', sa.Column(
        'payment_status',
        sa.Enum('NON_PAYE', 'PARTIEL', 'PAYE', 'EN_RETARD', name='paymentstatus', create_type=False),
        nullable=True
    ))

    # --- Autogenerated tables and columns ---
    op.create_table(
        'carts',
        sa.Column('client_id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'cart_items',
        sa.Column('cart_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reservation_expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['cart_id'], ['carts.id']),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'order_history',
        sa.Column('order_id', sa.UUID(), nullable=True),
        sa.Column('changed_by', sa.UUID(), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=True),
        sa.Column('old_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['changed_by'], ['users.id']),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'document_history',
        sa.Column('document_id', sa.UUID(), nullable=True),
        sa.Column('changed_by', sa.UUID(), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('old_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['changed_by'], ['users.id']),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'document_items',
        sa.Column('document_id', sa.UUID(), nullable=True),
        sa.Column('product_id', sa.UUID(), nullable=True),
        sa.Column('product_name', sa.String(length=255), nullable=True),
        sa.Column('product_sku', sa.String(length=100), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('unit_price', sa.Float(), nullable=False),
        sa.Column('discount_percent', sa.Float(), nullable=True),
        sa.Column('tax_percent', sa.Float(), nullable=True),
        sa.Column('subtotal', sa.Float(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id']),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'payments',
        sa.Column('document_id', sa.UUID(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('payment_method', sa.String(length=100), nullable=True),
        sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reference_number', sa.String(length=100), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('recorded_by', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id']),
        sa.ForeignKeyConstraint(['recorded_by'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # Add other new columns to documents, orders, and order_items
    op.add_column('documents', sa.Column('accepted_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('shipping_fee', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('paid_amount', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('remaining_amount', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('is_latest_version', sa.Boolean(), nullable=True))
    op.add_column('order_items', sa.Column('discount_percent', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('stock_reserved', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('reservation_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('orders', 'priced_at')


def downgrade() -> None:
    # Drop added columns and tables
    op.drop_column('orders', 'reservation_expires_at')
    op.drop_column('orders', 'stock_reserved')
    op.drop_column('orders', 'discount')
    op.drop_column('orders', 'processed_at')
    op.drop_column('order_items', 'subtotal')
    op.drop_column('order_items', 'discount_percent')
    op.drop_column('documents', 'is_latest_version')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'remaining_amount')
    op.drop_column('documents', 'paid_amount')
    op.drop_column('documents', 'payment_status')
    op.drop_column('documents', 'shipping_fee')
    op.drop_column('documents', 'discount')
    op.drop_column('documents', 'accepted_date')
    op.drop_table('payments')
    op.drop_table('document_items')
    op.drop_table('document_history')
    op.drop_table('order_history')
    op.drop_table('cart_items')
    op.drop_table('carts')

    # Drop ENUM type safely
    op.execute("DROP TYPE IF EXISTS paymentstatus")
    
    # Restore dropped column
    op.add_column('orders', sa.Column('priced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
