name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json
        
  dependency_scan:
    name: Run Safety Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run pip-audit on requirements.txt
        run: |
          pip install pip-audit
          pip-audit -r requirements/base.txt -f json -o pip-audit-report.json -v || true
      
      - name: Upload pip-audit report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pip-audit-report
          path: pip-audit-report.json

  code_quality:
    name: Run Code Quality
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Linting Tools
      run: pip install flake8
    - name: Run Flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    
  image_scan:
    name: Build Image and Run image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up Docker  
      uses: docker/setup-buildx-action@v3
       
    - name: Build Docker Image
      run: |
        docker build -t nour-backend:${{ github.sha }} .
        docker tag nour-backend:${{ github.sha }} nour-backend:latest

    - name: Install Docker Scout CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        chmod +x install-scout.sh
        ./install-scout.sh
        
    - name: Docker Scout Quick View
      run: docker scout quickview nour-backend:${{ github.sha }}

    - name: Docker Scout CVEs Scan
      run: |
        if [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker scout cves nour-backend:${{ github.sha }}
        else
          echo "DOCKER_PASSWORD secret not set. Running unauthenticated scan."
          docker scout cves --platform linux/amd64 nour-backend:${{ github.sha }}
        fi
